import os
import sys

# ─── Paths ───────────────────────────────────────────────────────────────────
BASE_DIR    = r"d:\Running\GZ-Valorant"
LOAD_DIR    = os.path.join(BASE_DIR, "load")
SDK_DIR     = os.path.join(BASE_DIR, "loaderDriver", "sdk")   # Only loaderDriver needs embedded binaries

XOR_KEY = 0xAB


def file_to_header(file_path: str, header_path: str, var_name: str) -> None:
    """Embed a binary file as a C unsigned char array."""
    with open(file_path, 'rb') as f:
        data = f.read()

    with open(header_path, 'w') as f:
        f.write('#pragma once\n')
        f.write('// Auto-generated by generate_headers.py  --  DO NOT EDIT\n')
        f.write(f'const unsigned char {var_name}[] = {{')
        for i, b in enumerate(data):
            if i % 12 == 0:
                f.write('\n    ')
            f.write(f'0x{b:02X}, ')
        f.write('\n};\n')
        f.write(f'const unsigned int {var_name}_size = {len(data)};\n')

    print(f'  [+] {os.path.basename(header_path)}  ({len(data):,} bytes)')


def driver_to_header_xor(driver_path: str, header_path: str, xor_key: int) -> None:
    """Embed driver.sys with XOR obfuscation."""
    with open(driver_path, 'rb') as f:
        data = f.read()

    encrypted = bytes([b ^ xor_key for b in data])

    with open(header_path, 'w') as f:
        f.write('#pragma once\n')
        f.write('// Auto-generated by generate_headers.py  --  DO NOT EDIT\n')
        f.write(f'// XOR key: 0x{xor_key:02X}\n')
        f.write('const unsigned char driver_data[] = {')
        for i, b in enumerate(encrypted):
            if i % 12 == 0:
                f.write('\n    ')
            f.write(f'0x{b:02X}, ')
        f.write('\n};\n')
        f.write(f'const unsigned int  driver_size    = {len(data)};\n')
        f.write(f'const unsigned char driver_xor_key = 0x{xor_key:02X};\n')

    print(f'  [+] {os.path.basename(header_path)}  ({len(data):,} bytes, XOR=0x{xor_key:02X})')


def main():
    print("=" * 60)
    print("  GZ-Valorant  --  Header Generator  (for loaderDriver)")
    print("  Replaces: load\\a.bat")
    print("=" * 60)

    # Verify source files exist
    kdu_path    = os.path.join(LOAD_DIR, "kdu.exe")
    drv64_path  = os.path.join(LOAD_DIR, "drv64.dll")
    driver_path = os.path.join(LOAD_DIR, "driver.sys")

    missing = [p for p in [kdu_path, drv64_path, driver_path] if not os.path.isfile(p)]
    if missing:
        print("\n[!] Missing source files:")
        for p in missing:
            print(f"    {p}")
        sys.exit(1)

    os.makedirs(SDK_DIR, exist_ok=True)
    print(f"\n  >> Output: {SDK_DIR}\n")

    file_to_header(kdu_path,   os.path.join(SDK_DIR, "kdu_data.h"),   "kdu_data")
    file_to_header(drv64_path, os.path.join(SDK_DIR, "drv64_data.h"), "drv64_data")
    driver_to_header_xor(driver_path, os.path.join(SDK_DIR, "driver_data.h"), XOR_KEY)

    print("\n[+] Done. Build loaderDriver.vcxproj to apply.")
    print("=" * 60)


if __name__ == "__main__":
    main()
