#include "overlay_menu.hpp"
#include "flick_weapon_catalog.hpp"
#include "../../sdk/core/console_log.hpp"
#include "../../sdk/core/app_paths.hpp"
#include "../../sdk/Utils/MacroEngine.h"
#include "../../../nlohmann/json.hpp"
#include <fstream>
#include <iostream>
#include <string>
void OverlayMenu::SaveConfig(const char* path) {
    try {
        nlohmann::json j;
        j["visual_style_version"] = 2;
        j["esp_toggle"] = esp_toggle;
        j["esp_icons"] = esp_icons;
        j["esp_font_size"] = esp_font_size;
        j["name_font_size"] = name_font_size;
        j["distance_font_size"] = distance_font_size;
        j["weapon_font_size"] = weapon_font_size;
        j["rank_font_size"] = rank_font_size;
        j["teamid_badge_size"] = teamid_badge_size;
        j["kill_font_size"] = kill_font_size;
        j["survival_level_font_size"] = survival_level_font_size;
        j["damage_font_size"] = damage_font_size;
        j["speed_font_size"] = speed_font_size;
        j["ammo_font_size"] = ammo_font_size;
        j["spectated_font_size"] = spectated_font_size;
        j["weapon_icon_size"] = weapon_icon_size;
        j["esp_text_background"] = esp_text_background;
        j["esp_text_bg_alpha"] = esp_text_bg_alpha;
        j["esp_health_text"] = esp_health_text;
        j["esp_health_display_mode"] = esp_health_display_mode;
        j["esp_health_bar_style"] = esp_health_bar_style;
        j["esp_aim_warning"] = esp_aim_warning;
        j["esp_view_direction"] = esp_view_direction;
        j["esp_status_badges"] = esp_status_badges;
        j["esp_close_warning"] = esp_close_warning;
        j["esp_close_warning_distance"] = esp_close_warning_distance;
        j["esp_view_direction_length"] = esp_view_direction_length;
        j["box_thickness"] = box_thickness;
        j["esp_skeleton_dots"] = esp_skeleton_dots;
        j["esp_spectator_list"] = esp_spectator_list;
        j["player_list_enabled"] = player_list_enabled;
        j["player_list_hold_required"] = player_list_hold_required;
        j["player_list_hold_key"] = player_list_hold_key;
        j["debug_loot_resolver"] = debug_loot_resolver;
        j["active_preset"] = active_preset;
        j["flick_enabled"] = flick_enabled;
        j["flick_visible_only"] = flick_visible_only;
        j["flick_auto_shot"] = true;
        j["flick_shot_hold"] = flick_shot_hold;
        j["flick_behavior_mode"] = flick_behavior_mode;
        j["flick_follow_auto_shot"] = flick_follow_auto_shot;
        FlickWeaponCatalog::EnsureCategoryDefaults(flick_category_enabled);
        FlickWeaponCatalog::EnsureCategoryBoolDefaults(flick_category_visible_only, flick_visible_only);
        FlickWeaponCatalog::EnsureCategoryBoolDefaults(flick_category_shot_hold, flick_shot_hold);
        FlickWeaponCatalog::EnsureCategoryBoolDefaults(flick_category_follow_auto_shot, flick_follow_auto_shot);
        FlickWeaponCatalog::EnsureCategoryIntDefaults(flick_category_behavior_mode, flick_behavior_mode);
        FlickWeaponCatalog::EnsureCategoryIntDefaults(flick_category_target_part, flick_target_part);
        FlickWeaponCatalog::EnsureCategoryIntDefaults(flick_category_key, flick_key);
        FlickWeaponCatalog::EnsureCategoryFloatDefaults(flick_category_max_dist, flick_max_dist);
        FlickWeaponCatalog::EnsureCategoryMoveSpeedDefaults(flick_category_move_speed);
        FlickWeaponCatalog::EnsureCategoryFovDefaults(flick_category_fov, flick_fov);
        j["flick_category_enabled"] = flick_category_enabled;
        j["flick_category_visible_only"] = flick_category_visible_only;
        j["flick_category_shot_hold"] = flick_category_shot_hold;
        j["flick_category_follow_auto_shot"] = flick_category_follow_auto_shot;
        j["flick_category_behavior_mode"] = flick_category_behavior_mode;
        j["flick_category_target_part"] = flick_category_target_part;
        j["flick_category_key"] = flick_category_key;
        j["flick_category_max_dist"] = flick_category_max_dist;
        j["flick_category_move_speed"] = flick_category_move_speed;
        j["flick_category_fov"] = flick_category_fov;
        j["flick_return"] = flick_return;
        j["flick_fov"] = flick_fov;
        j["flick_max_dist"] = flick_max_dist;
        j["flick_target_part"] = flick_target_part;
        j["flick_key"] = flick_key;
        j["flick_key2"] = flick_key2;
        j["flick_weapon_s686"] = flick_weapon_s686;
        j["flick_weapon_s12k"] = flick_weapon_s12k;
        j["flick_weapon_s1897"] = flick_weapon_s1897;
        j["flick_weapon_dbs"] = flick_weapon_dbs;
        j["flick_weapon_o12"] = flick_weapon_o12;
        j["flick_weapon_slr"] = flick_weapon_slr;
        j["flick_weapon_mini14"] = flick_weapon_mini14;
        j["flick_weapon_sks"] = flick_weapon_sks;
        j["flick_weapon_vss"] = flick_weapon_vss;
        j["flick_weapon_qbu"] = flick_weapon_qbu;
        j["flick_weapon_kar98k"] = flick_weapon_kar98k;
        j["flick_weapon_m24"] = flick_weapon_m24;
        j["flick_weapon_awm"] = flick_weapon_awm;
        j["flick_weapon_lynx"] = flick_weapon_lynx;
        j["flick_weapon_win94"] = flick_weapon_win94;
        j["flick_weapon_mosin"] = flick_weapon_mosin;
        j["flick_weapon_panzerfaust"] = flick_weapon_panzerfaust;
        j["flick_weapon_mk12"] = flick_weapon_mk12;
        j["flick_weapon_mk14"] = flick_weapon_mk14;
        j["flick_weapon_dragunov"] = flick_weapon_dragunov;
        j["esp_show_enemies"] = esp_show_enemies;
        j["esp_show_teammates"] = esp_show_teammates;
        j["esp_offscreen"] = esp_offscreen;
        j["esp_offscreen_text"] = esp_offscreen_text;
        j["esp_offscreen_style"] = esp_offscreen_style;
        j["offscreen_color_mode"] = offscreen_color_mode;
        j["offscreen_radius"] = offscreen_radius;
        j["offscreen_size"] = offscreen_size;
        j["offscreen_near_color"] = { offscreen_near_color[0], offscreen_near_color[1], offscreen_near_color[2], offscreen_near_color[3] };
        j["offscreen_far_color"] = { offscreen_far_color[0], offscreen_far_color[1], offscreen_far_color[2], offscreen_far_color[3] };
        j["esp_box"] = esp_box;
        j["esp_box_type"] = esp_box_type;
        j["esp_skeleton"] = esp_skeleton;
        j["esp_name"] = esp_name;
        j["esp_distance"] = esp_distance;
        j["esp_health"] = esp_health;
        j["esp_health_pos"] = esp_health_pos;
        j["esp_distance_pos"] = esp_distance_pos;
        j["esp_name_pos"] = esp_name_pos;
        j["esp_rank_pos"] = esp_rank_pos;
        j["esp_weapon_pos"] = esp_weapon_pos;
        j["esp_spectated_pos"] = esp_spectated_pos;
        j["esp_teamid_pos"] = esp_teamid_pos;
        j["esp_killcount_pos"] = esp_killcount_pos;
        j["esp_survival_level_pos"] = esp_survival_level_pos;
        j["esp_damage_pos"] = esp_damage_pos;
        j["esp_speed_pos"] = esp_speed_pos;
        j["esp_ammo_pos"] = esp_ammo_pos;
        j["esp_items"] = esp_items;
        j["esp_items_toggle_key"] = esp_items_toggle_key;
        j["esp_vehicles_toggle_key"] = esp_vehicles_toggle_key;
        j["esp_snapline"] = esp_snapline;
        j["snapline_type"] = snapline_type;
        j["esp_weapon"] = esp_weapon;
        j["esp_damage"] = esp_damage;
        j["esp_speed"] = esp_speed;
        j["esp_ammo"] = esp_ammo;
        j["esp_weapon_type"] = esp_weapon_type;
        j["esp_fillbox"] = esp_fillbox;
        j["render_distance"] = render_distance;
        j["language"] = language;
        j["show_macro_overlay"] = show_macro_overlay;
        j["show_radar_center"] = show_radar_center;
        j["radar_enabled"] = radar_enabled;
        j["radar_offset_x"] = radar_offset_x;
        j["radar_offset_y"] = radar_offset_y;
        j["radar_zoom_multiplier"] = radar_zoom_multiplier;
        j["radar_scale"] = radar_scale;
        j["radar_dot_size"] = radar_dot_size;
        j["radar_rotation_offset"] = radar_rotation_offset;
        j["minimap_enabled"] = minimap_enabled;
        j["bigmap_enabled"] = bigmap_enabled;
        j["minimap_show_direction"] = minimap_show_direction;
        j["minimap_fire_trace"] = minimap_fire_trace;
        j["minimap_view_ray_length"] = minimap_view_ray_length;
        j["minimap_fire_ray_length"] = minimap_fire_ray_length;
        j["minimap_fire_flash_ms"] = minimap_fire_flash_ms;
        j["minimap_ray_width"] = minimap_ray_width;
        j["bigmap_show_names"] = bigmap_show_names;
        j["bigmap_show_direction"] = bigmap_show_direction;
        j["bigmap_name_background"] = bigmap_name_background;
        j["bigmap_show_legend"] = bigmap_show_legend;
        j["bigmap_show_vehicles"] = bigmap_show_vehicles;
        j["bigmap_show_airdrops"] = bigmap_show_airdrops;
        j["bigmap_show_deadboxes"] = bigmap_show_deadboxes;
        j["bigmap_marker_size"] = bigmap_marker_size;
        j["bigmap_marker_alpha"] = bigmap_marker_alpha;
        j["bigmap_icon_size"] = bigmap_icon_size;
        j["bigmap_name_font_size"] = bigmap_name_font_size;
        j["bigmap_name_bg_alpha"] = bigmap_name_bg_alpha;
        j["bigmap_offset_x"] = bigmap_offset_x;
        j["bigmap_offset_y"] = bigmap_offset_y;
        j["bigmap_screen_scale"] = bigmap_screen_scale;
        j["anti_screenshot"] = anti_screenshot;
        j["macro_enabled"] = macro_enabled;
        j["macro_humanize"] = macro_humanize;
        j["macro_ads_only"] = macro_ads_only;
        j["macro_global_multiplier"] = MacroEngine::global_multiplier;
        j["macro_overlay_color"] = { macro_overlay_color[0], macro_overlay_color[1], macro_overlay_color[2], macro_overlay_color[3] };

        j["esp_items"] = esp_items;
        j["esp_vehicles"] = esp_vehicles;
        j["esp_airdrops"] = esp_airdrops;
        j["esp_deadboxes"] = esp_deadboxes;
        j["loot_max_dist"] = loot_max_dist;
        j["vehicle_max_dist"] = vehicle_max_dist;
        j["item_icon_size"] = item_icon_size;
        j["item_group_icon_size"] = item_group_icon_size;
        j["vehicle_icon_size"] = vehicle_icon_size;
        j["loot_distance_font_size"] = loot_distance_font_size;
        j["asset_animation_enabled"] = asset_animation_enabled;
        j["asset_animation_glow"] = asset_animation_glow;
        j["asset_animation_shine"] = asset_animation_shine;
        j["asset_animation_strength"] = asset_animation_strength;
        j["asset_animation_speed"] = asset_animation_speed;

        j["share_radar"] = share_radar;
        j["share_radar_ip"] = std::string(share_radar_ip);
        j["esp_grenade_prediction"] = esp_grenade_prediction;
        j["esp_projectile_tracer"] = esp_projectile_tracer;
        j["esp_threat_warning"] = esp_threat_warning;

        j["loot_armor_lv1"] = loot_armor_lv1;
        j["loot_armor_lv2"] = loot_armor_lv2;
        j["loot_armor_lv3"] = loot_armor_lv3;
        j["loot_helmet_lv1"] = loot_helmet_lv1;
        j["loot_helmet_lv2"] = loot_helmet_lv2;
        j["loot_helmet_lv3"] = loot_helmet_lv3;
        j["loot_meds_boosts"] = loot_meds_boosts;
        j["loot_meds_healing"] = loot_meds_healing;
        j["loot_ammo_all"] = loot_ammo_all;
        j["loot_ammo_high"] = loot_ammo_high;
        j["loot_scopes_all"] = loot_scopes_all;
        j["loot_scopes_high"] = loot_scopes_high;
        j["loot_attach_mag"] = loot_attach_mag;
        j["loot_attach_muzzle"] = loot_attach_muzzle;
        j["loot_weapon_special"] = loot_weapon_special;
        j["loot_weapon_all"] = loot_weapon_all;
        j["loot_backpack_lv1"] = loot_backpack_lv1;
        j["loot_backpack_lv2"] = loot_backpack_lv2;
        j["loot_backpack_lv3"] = loot_backpack_lv3;
        j["loot_ghillie"] = loot_ghillie;
        j["loot_utility"] = loot_utility;
        j["loot_repair"] = loot_repair;
        j["loot_ammo_556"] = loot_ammo_556; j["loot_ammo_762"] = loot_ammo_762;
        j["loot_ammo_9mm"] = loot_ammo_9mm; j["loot_ammo_45"] = loot_ammo_45;
        j["loot_ammo_12g"] = loot_ammo_12g; j["loot_ammo_300"] = loot_ammo_300;
        j["loot_ammo_slug"] = loot_ammo_slug; j["loot_ammo_57"] = loot_ammo_57;
        j["loot_ammo_40"] = loot_ammo_40;
        j["loot_ammo_bolt"] = loot_ammo_bolt; j["loot_ammo_flare"] = loot_ammo_flare;
        j["loot_ammo_mortar"] = loot_ammo_mortar;

        j["loot_key_security"] = loot_key_security; j["loot_key_secret"] = loot_key_secret;
        j["loot_key_taego"] = loot_key_taego; j["loot_key_vikendi"] = loot_key_vikendi;
        j["loot_key_chimera"] = loot_key_chimera; j["loot_key_haven"] = loot_key_haven;

        j["loot_scope_reddot"] = loot_scope_reddot; j["loot_scope_holo"] = loot_scope_holo;
        j["loot_scope_2x"] = loot_scope_2x; j["loot_scope_3x"] = loot_scope_3x;
        j["loot_scope_4x"] = loot_scope_4x; j["loot_scope_6x"] = loot_scope_6x;
        j["loot_scope_8x"] = loot_scope_8x; j["loot_scope_15x"] = loot_scope_15x;
        j["loot_scope_thermal"] = loot_scope_thermal;
        j["loot_muzzle_comp"] = loot_muzzle_comp; j["loot_muzzle_flash"] = loot_muzzle_flash;
        j["loot_muzzle_supp"] = loot_muzzle_supp; j["loot_muzzle_choke"] = loot_muzzle_choke;
        j["loot_grip_vertical"] = loot_grip_vertical; j["loot_grip_angled"] = loot_grip_angled;
        j["loot_grip_half"] = loot_grip_half; j["loot_grip_thumb"] = loot_grip_thumb;
        j["loot_grip_light"] = loot_grip_light; j["loot_stock_heavy"] = loot_stock_heavy;
        j["loot_stock_cheek"] = loot_stock_cheek; j["loot_mag_ext"] = loot_mag_ext;
        j["loot_mag_quick"] = loot_mag_quick; j["loot_mag_ext_quick"] = loot_mag_ext_quick;

        j["loot_throw_frag"] = loot_throw_frag; j["loot_throw_smoke"] = loot_throw_smoke;
        j["loot_throw_flash"] = loot_throw_flash; j["loot_throw_molotov"] = loot_throw_molotov;
        j["loot_throw_c4"] = loot_throw_c4; j["loot_throw_sticky"] = loot_throw_sticky;
        j["loot_throw_bz"] = loot_throw_bz; j["loot_throw_decoy"] = loot_throw_decoy;

        j["loot_attach_grip"] = loot_attach_grip;
        j["loot_attach_stock"] = loot_attach_stock;
        j["loot_attach_scope_all"] = loot_attach_scope_all;
        j["loot_attach_scope_high"] = loot_attach_scope_high;

        // Weapon-specific booleans
        j["lw_ace32"] = loot_weapon_ace32; j["lw_ak47"] = loot_weapon_ak47;
        j["lw_aug"] = loot_weapon_aug; j["lw_beryl"] = loot_weapon_beryl;
        j["lw_g36c"] = loot_weapon_g36c; j["lw_groza"] = loot_weapon_groza;
        j["lw_hk416"] = loot_weapon_hk416; j["lw_k2"] = loot_weapon_k2;
        j["lw_m16"] = loot_weapon_m16; j["lw_mutant"] = loot_weapon_mutant;
        j["lw_qbz"] = loot_weapon_qbz; j["lw_scar"] = loot_weapon_scar;
        j["lw_famas"] = loot_weapon_famas; j["lw_awm"] = loot_weapon_awm;
        j["lw_kar98"] = loot_weapon_kar98; j["lw_m24"] = loot_weapon_m24;
        j["lw_mosin"] = loot_weapon_mosin; j["lw_win94"] = loot_weapon_win94;
        j["lw_dragunov"] = loot_weapon_dragunov; j["lw_mini14"] = loot_weapon_mini14;
        j["lw_mk12"] = loot_weapon_mk12; j["lw_mk14"] = loot_weapon_mk14;
        j["lw_qbu"] = loot_weapon_qbu; j["lw_sks"] = loot_weapon_sks;
        j["lw_vss"] = loot_weapon_vss; j["lw_slr"] = loot_weapon_slr;
        j["lw_bizon"] = loot_weapon_bizon; j["lw_mp5"] = loot_weapon_mp5;
        j["lw_mp9"] = loot_weapon_mp9; j["lw_p90"] = loot_weapon_p90;
        j["lw_thompson"] = loot_weapon_thompson; j["lw_ump"] = loot_weapon_ump;
        j["lw_uzi"] = loot_weapon_uzi; j["lw_vector"] = loot_weapon_vector;
        j["lw_js9"] = loot_weapon_js9; j["lw_dp28"] = loot_weapon_dp28;
        j["lw_m249"] = loot_weapon_m249; j["lw_mg3"] = loot_weapon_mg3;
        j["lw_dp12"] = loot_weapon_dp12; j["lw_saiga"] = loot_weapon_saiga;
        j["lw_deagle"] = loot_weapon_deagle; j["lw_m1911"] = loot_weapon_m1911;
        j["lw_p92"] = loot_weapon_p92; j["lw_skorpion"] = loot_weapon_skorpion;
        j["lw_nagant"] = loot_weapon_nagant; j["lw_rhino"] = loot_weapon_rhino;
        j["lw_stungun"] = loot_weapon_stungun;
        j["lw_pan"] = loot_weapon_pan; j["lw_flare"] = loot_weapon_flare;
        j["lw_crossbow"] = loot_weapon_crossbow; j["lw_panzer"] = loot_weapon_panzer;
        j["lw_spike"] = loot_weapon_spike; j["lw_m79"] = loot_weapon_m79;

        j["loot_ghillie_arctic"] = loot_ghillie_arctic;
        j["loot_ghillie_desert"] = loot_ghillie_desert;
        j["loot_ghillie_jungle"] = loot_ghillie_jungle;
        j["loot_ghillie_forest"] = loot_ghillie_forest;
        j["loot_ghillie_mossy"] = loot_ghillie_mossy;
        j["loot_ghillie_brown"] = loot_ghillie_brown;

        j["loot_utility_drone"] = loot_utility_drone;
        j["loot_utility_scope"] = loot_utility_scope;
        j["loot_repair_armor"] = loot_repair_armor;
        j["loot_repair_helmet"] = loot_repair_helmet;
        j["loot_repair_vehicle"] = loot_repair_vehicle;
        j["loot_utility_jammer"] = loot_utility_jammer;
        j["loot_utility_bluechip"] = loot_utility_bluechip;
        j["loot_utility_vtransmitter"] = loot_utility_vtransmitter;
        j["loot_utility_shield"] = loot_utility_shield;

        j["loot_vehicle_uaz"] = loot_vehicle_uaz;
        j["loot_vehicle_dacia"] = loot_vehicle_dacia;
        j["loot_vehicle_buggy"] = loot_vehicle_buggy;
        j["loot_vehicle_bike"] = loot_vehicle_bike;
        j["loot_vehicle_boat"] = loot_vehicle_boat;
        j["loot_vehicle_air"] = loot_vehicle_air;
        j["loot_vehicle_brdm"] = loot_vehicle_brdm;
        j["loot_vehicle_scooter"] = loot_vehicle_scooter;
        j["loot_vehicle_tuk"] = loot_vehicle_tuk;
        j["loot_vehicle_snow"] = loot_vehicle_snow;
        j["loot_vehicle_bus"] = loot_vehicle_bus;
        j["loot_vehicle_truck"] = loot_vehicle_truck;
        j["loot_vehicle_train"] = loot_vehicle_train;
        j["loot_vehicle_mirado"] = loot_vehicle_mirado;
        j["loot_vehicle_pickup"] = loot_vehicle_pickup;
        j["loot_vehicle_rony"] = loot_vehicle_rony;
        j["loot_vehicle_blanc"] = loot_vehicle_blanc;

        j["esp_distance_lod"] = esp_distance_lod;
        j["skeleton_max_dist"] = skeleton_max_dist;
        j["name_max_dist"] = name_max_dist;
        j["weapon_max_dist"] = weapon_max_dist;
        j["box_max_dist"] = box_max_dist;
        j["hp_max_dist"] = hp_max_dist;
        j["distance_txt_max_dist"] = distance_txt_max_dist;

        j["color_box_vis"] = { box_visible_color[0], box_visible_color[1], box_visible_color[2], box_visible_color[3] };
        j["color_box_inv"] = { box_invisible_color[0], box_invisible_color[1], box_invisible_color[2], box_invisible_color[3] };
        j["color_skel_vis"] = { skeleton_visible_color[0], skeleton_visible_color[1], skeleton_visible_color[2], skeleton_visible_color[3] };
        j["color_skel_inv"] = { skeleton_invisible_color[0], skeleton_invisible_color[1], skeleton_invisible_color[2], skeleton_invisible_color[3] };
        j["color_names"] = { name_visible_color[0], name_visible_color[1], name_visible_color[2], name_visible_color[3] };
        j["color_name_vis"] = { name_visible_color[0], name_visible_color[1], name_visible_color[2], name_visible_color[3] };
        j["color_name_inv"] = { name_invisible_color[0], name_invisible_color[1], name_invisible_color[2], name_invisible_color[3] };
        j["color_dist"] = { distance_color[0], distance_color[1], distance_color[2], distance_color[3] };
        j["color_weapon"] = { weapon_color[0], weapon_color[1], weapon_color[2], weapon_color[3] };
        j["color_rank"] = { rank_color[0], rank_color[1], rank_color[2], rank_color[3] };
        j["color_teamid"] = { teamid_color[0], teamid_color[1], teamid_color[2], teamid_color[3] };
        j["color_kill"] = { kill_color[0], kill_color[1], kill_color[2], kill_color[3] };
        j["color_survival_level"] = { survival_level_color[0], survival_level_color[1], survival_level_color[2], survival_level_color[3] };
        j["color_damage"] = { damage_color[0], damage_color[1], damage_color[2], damage_color[3] };
        j["color_speed"] = { speed_color[0], speed_color[1], speed_color[2], speed_color[3] };
        j["color_ammo"] = { ammo_color[0], ammo_color[1], ammo_color[2], ammo_color[3] };
        j["color_spectated"] = { spectated_color[0], spectated_color[1], spectated_color[2], spectated_color[3] };
        j["color_aim_warning"] = { aim_warning_color[0], aim_warning_color[1], aim_warning_color[2], aim_warning_color[3] };
        j["color_close_warning"] = { close_warning_color[0], close_warning_color[1], close_warning_color[2], close_warning_color[3] };
        j["color_view_direction"] = { view_direction_color[0], view_direction_color[1], view_direction_color[2], view_direction_color[3] };
        j["team_color_custom"] = team_color_custom;
        j["team_custom_colors"] = {
            { team_custom_colors[0][0], team_custom_colors[0][1], team_custom_colors[0][2], team_custom_colors[0][3] },
            { team_custom_colors[1][0], team_custom_colors[1][1], team_custom_colors[1][2], team_custom_colors[1][3] },
            { team_custom_colors[2][0], team_custom_colors[2][1], team_custom_colors[2][2], team_custom_colors[2][3] },
            { team_custom_colors[3][0], team_custom_colors[3][1], team_custom_colors[3][2], team_custom_colors[3][3] }
        };
        j["esp_multilayer_nameplate"] = esp_multilayer_nameplate;

        const std::string resolvedPath = AppPaths::RuntimePath(path ? path : "settings.json");
        std::ofstream file(resolvedPath);
        if (file.is_open()) {
            file << j.dump(4);
            file.close();
            UTN_DEV_LOG(std::cout << "[DEV] Saved Config to: " << resolvedPath << std::endl);
        }
    } catch (...) {}
}
